baseURL: https://zainraza.net 
languageCode: en-us
title: Zain's Blog
theme: "PaperMod"
paginate: 15

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Zain's Blog
  description: Welcome to my blog. Here I use zoomer lang to describe my experiences in tech. Terrible takes are authentically mine. 
  keywords: [Blog, Computer Science]
  author: Zain Raza
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: false

  ShowReadingTime: true
  # ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  # ShowCodeCopyButtons: false
  ShowCodeCopyButtons: true
  # ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  # UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  # comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  # showtoc: false
  tocopen: false

  label:
    text: "Zain's Blog"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Zain's Blog
    subtitle: "realest blog known to man"
    # imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog. Here I use zoomer lang to describe my experiences in tech. Terrible takes are authentically mine.

  socialIcons:
    - name: github
      url: "https://github.com/zainaraza43"
    - name: linkedin
      url: "https://www.linkedin.com/in/zainr/"
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
  - name: "About"
    url: "/about/"
  - name: "Posts"
    url: "/posts/"
  - name: "Search"
    url: "/search/"
